bundler_args: "--without development"
before_script:
  - "sudo apt-get update && sudo apt-get dist-upgrade && sudo apt-get install dtach"
script: "bundle exec rake"
rvm:
  - 1.8.7
  - 1.9.2
  - jruby
  - rbx